# Generated by Django 6.0 on 2025-12-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerpricealert', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertsubscription',
            old_name='target_price',
            new_name='target_max',
        ),
        migrations.AddField(
            model_name='alertsubscription',
            name='target_min',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
            preserve_default=False,
        ),
    ]
