# Generated by Django 5.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerpricealert', '0006_rename_target_price_alertsubscription_target_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(unique=True, blank=False, max_length=254),
        ),
    ]
